module.exports = {
  ApiKey: require('./ApiKey'),
  Assessment: require('./Assessment'),
  Asset: require('./Asset'),
  AssetType: require('./AssetType'),
  AuthMean: require('./AuthMean'),
  AuthToken: require('./AuthToken'),
  Availability: require('./Availability'),
  Category: require('./Category'),
  Config: require('./Config'),
  CustomAttribute: require('./CustomAttribute'),
  Document: require('./Document'),
  Entry: require('./Entry'),
  // Event: require('./Event'),
  Message: require('./Message'),
  Order: require('./Order'),
  Role: require('./Role'),
  SavedSearch: require('./SavedSearch'),
  Task: require('./Task'),
  Transaction: require('./Transaction'),
  User: require('./User'),
  Webhook: require('./Webhook'),
  WebhookLog: require('./WebhookLog'),
  Workflow: require('./Workflow'),
  WorkflowLog: require('./WorkflowLog'),

  InternalAvailability: require('./InternalAvailability'),
}
